services:
  user-auth-service:
    build: .
    container_name: user-auth-service
    restart: always
    env_file:
      - .env   # add this line to load .env automatically
    ports:
      - "8007:8007"
    networks:
      - dhwaniastro-net

networks:
  dhwaniastro-net:
    external: true