services:
  user-auth-service:
    build: .
    container_name: user-auth-service
    restart: always
    env_file:
      - .env
    ports:
      - "8007:8007"
    networks:
      - dhwaniastro-net

    mem_limit: 50m       
    memswap_limit: 50m    

networks:
  dhwaniastro-net:
    external: true