
const OTP_EXPIRY = 300; 
const OTP_RATE_LIMIT = 3;
const OTP_RATE_WINDOW = 600; 
const LOGIN_ATTEMPT_LIMIT = 5; 
const LOGIN_ATTEMPT_WINDOW = 900; 

module.exports = {
  OTP_EXPIRY,
  OTP_RATE_LIMIT,
  OTP_RATE_WINDOW,
  LOGIN_ATTEMPT_LIMIT,
  LOGIN_ATTEMPT_WINDOW,
};

